name: Run Python Tests

on:
  push:
    branches:
      - master
      - feat/tests
  pull_request:
    branches:
      - master
      - develop
      - feat/tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Run tests
        run: python -m unittest discover tests
